# Reference configuration for a simple 3-node Tinode cluster.
# Includes:
# * Mysql database
# * 3 Tinode servers
# * 3 exporters

version: '3.4'

# Base Tinode template.
x-tinode:
  &tinode-base
  depends_on:
    - mysql
  image: tinode/tinode:latest
  restart: always

x-exporter:
  &exporter-base
  image: tinode/exporter:latest
  restart: always
  networks:
    internal:

x-tinode-env-vars: &tinode-env-vars
  "STORE_USE_ADAPTER": "mysql"
  "DEFAULT_SAMPLE_DATA": ""
  "PPROF_URL": "/pprof"
  # You can provide your own tinode config by setting EXT_CONFIG env var and binding your configuration file to
  # "EXT_CONFIG": "/etc/tinode/tinode.conf"
  "WAIT_FOR": "mysql:3306"
  # Web client push notifications.
  # Modify as appropriate.
  # To enable Tinode server push notifications, please refer to the "push" section of your tinode.conf.
  "FCM_PUSH_ENABLED": "true"
  "FCM_API_KEY": "AIzaSyD6X4ULR-RUsobvs1zZ2bHdJuPz39q2tbQ"
  "FCM_APP_ID": "1:114126160546:web:aca6ea2981feb81fb44dfb"
  "FCM_PROJECT_ID": "tinode-1000"
  "FCM_SENDER_ID": 114126160546
  "FCM_VAPID_KEY": "BOgQVPOMzIMXUpsYGpbVkZoEBc0ifKY_f2kSU5DNDGYI6i6CoKqqxDd7w7PJ3FaGRBgVGJffldETumOx831jl58"
  # iOS app universal links configuration.
  # "IOS_UNIV_LINKS_APP_ID": "<ios universal links app id>"

x-exporter-env-vars: &exporter-env-vars
  "TINODE_ADDR": "http://tinode.host:18080/stats/expvar/"
  # Prometheus configuration:
  "SERVE_FOR": "prometheus"
  "PROM_NAMESPACE": "tinode"
  "PROM_METRICS_PATH": "/metrics"
  #
  # InfluxDB configation:
  # "SERVE_FOR": "influxdb"
  # "INFLUXDB_VERSION": 1.7
  # "INFLUXDB_ORGANIZATION": "<your organization>"
  # "INFLUXDB_PUSH_INTERVAL": 30
  # "INFLUXDB_PUSH_ADDRESS": "https://mon.tinode.co/intake"
  # "INFLUXDB_AUTH_TOKEN": "abcdef"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      internal:
        ipv4_address: 172.19.0.3
    # Use your own volume.
    # volumes:
    #   - <mysql directory in your file system>:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Tinode servers.
  tinode-0:
    << : *tinode-base
    container_name: tinode-0
    hostname: tinode-0
    networks:
      internal:
        ipv4_address: 172.19.0.5
    # You can mount your volumes as necessary:
    # volumes:
    #   # E.g. external config (assuming EXT_CONFIG is set).
    #   - <path to your tinode.conf>:/etc/tinode/tinode.conf
    #   # Logs directory.
    #   - <path to your tinode-0 logs directory>:/var/log
    ports:
      - "6060:18080"
    environment:
      << : *tinode-env-vars
      "CLUSTER_SELF": "tinode-0"
      # Uncomment the lines below if you wish to upgrade or reset the database.
      # "UPGRADE_DB": "true"
      # "RESET_DB": "true"

  tinode-1:
    << : *tinode-base
    container_name: tinode-1
    hostname: tinode-1
    networks:
      internal:
        ipv4_address: 172.19.0.6
    # You can mount your volumes as necessary:
    # volumes:
    #   # E.g. external config (assuming EXT_CONFIG is set).
    #   - <path to your tinode.conf>:/etc/tinode/tinode.conf
    #   # Logs directory.
    #   - <path to your tinode-1 logs directory>:/var/log
    ports:
      - "6061:18080"
    environment:
      << : *tinode-env-vars
      "CLUSTER_SELF": "tinode-1"
      "WAIT_FOR": "tinode-0:18080"

  tinode-2:
    << : *tinode-base
    container_name: tinode-2
    hostname: tinode-2
    networks:
      internal:
        ipv4_address: 172.19.0.7
    # You can mount your volumes as necessary:
    # volumes:
    #   # E.g. external config (assuming EXT_CONFIG is set).
    #   - <path to your tinode.conf>:/etc/tinode/tinode.conf
    #   # Logs directory.
    #   - <path to your tinode-2 logs directory>:/var/log
    ports:
      - "6062:18080"
    environment:
      << : *tinode-env-vars
      "CLUSTER_SELF": "tinode-2"
      "WAIT_FOR": "tinode-0:18080"

  # Monitoring.
  # Exporters are paired with tinode instances.
  exporter-0:
    << : *exporter-base
    container_name: exporter-0
    hostname: exporter-0
    depends_on:
      - tinode-0
    ports:
      - "6222:6222"
    environment:
      << : *exporter-env-vars
      "INSTANCE": "tinode-exp-0"
      "WAIT_FOR": "tinode-0:18080"
    extra_hosts:
      - "tinode.host:172.19.0.5"

  exporter-1:
    << : *exporter-base
    container_name: exporter-1
    hostname: exporter-1
    depends_on:
      - tinode-1
    ports:
      - "6223:6222"
    environment:
      << : *exporter-env-vars
      "INSTANCE": "tinode-exp-1"
      "WAIT_FOR": "tinode-1:18080"
    extra_hosts:
      - "tinode.host:172.19.0.6"

  exporter-2:
    << : *exporter-base
    container_name: exporter-2
    hostname: exporter-2
    depends_on:
      - tinode-2
    ports:
      - "6224:6222"
    environment:
      << : *exporter-env-vars
      "INSTANCE": "tinode-exp-2"
      "WAIT_FOR": "tinode-2:18080"
    extra_hosts:
      - "tinode.host:172.19.0.7"

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.19.0.0/24"
